# i need. the. kernel source.

BOARD_VENDOR := xiaomi

DEVICE_PATH := device/xiaomi/serenity

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a75
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

TARGET_BOARD_PLATFORM := ums9230

TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
TARGET_PREBUILT_RAMDISK := $(DEVICE_PATH)/prebuilt/ramdisk.cpio
BOARD_USES_VENDOR_RAMDISK := true
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_KERNEL_IMAGE_NAME := Image.gz

BOARD_BOOTCONFIG += androidboot.hardware=serenity
BOARD_BOOTCONFIG += androidboot.dtbo_idx=0

BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8 bootconfig bootconfig
BOARD_KERNEL_PAGESIZE := 4096
BOARD_BOOTIMG_HEADER_VERSION := 4

BOARD_USES_RECOVERY_AS_BOOT := true
